version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: Asia/Jakarta
    groups:
      dependencies:
        patterns: ['*']

  - package-ecosystem: bun
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
      timezone: Asia/Jakarta
    groups:
      drizzle:
        patterns: ['drizzle-*']
      nodemailer:
        patterns: ['@types/nodemailer', 'nodemailer']
      otel:
        patterns: ['@elysiajs/opentelemetry', '@opentelemetry/*']
        update-types: patch
      openapi:
        patterns: ['@elysiajs/openapi', 'openapi-types']
        update-types: patch
      pino:
        patterns: ['pino', 'pino-pretty']
