integration:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**.yml'
          - 'compose.yml'
          - 'compose.*.yml'

github_actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**.yml'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '.env.example'
          - '**.md'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'bun.lock'

deployment:
  - changed-files:
      - any-glob-to-any-file:
          - 'deploy/docker/**'
          - 'compose.yml'
          - 'compose.*.yml'

api:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/modules/*/*.controller.ts'
          - 'src/utils/*.util.ts'
          - 'src/routes/*.route.ts'
          - 'test/routes/*.route.test.ts'
          - 'test/utils/*.util.test.ts'

auth:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/modules/auth/**'
          - 'src/*/auth.*.ts'
          - 'test/*/auth.*.test.ts'

mail:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/*/mail.*.ts'
          - 'test/*/mail.*.test.ts'

otel:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/*/otel.*.ts'
          - 'test/*/otel.*.test.ts'

feeds:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/modules/feeds/**'

database:
  - changed-files:
      - any-glob-to-any-file:
          - 'database/**'
          - 'src/*/database.*.ts'
          - 'src/modules/*/schemas/*.schema.ts'
          - 'test/*/database.*.test.ts'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'test/**.test.ts'

enhancement:
  - changed-files:
      - any-glob-to-any-file: '**'
