services:
  app:
    extends:
      file: deploy/compose.yml
      service: app
    image: ghcr.io/feryardiant/learn-bun-elysia:local
    pull_policy: never
    ports:
      - 127.0.0.1:${FORWARD_APP_PORT:-3000}:3000
      - 127.0.0.1:${FORWARD_STUDIO_PORT:-4000}:4000
    environment:
      NODE_ENV: ${NODE_ENV:-local}

  postgres:
    extends:
      file: deploy/compose.yml
      service: postgres
    ports:
      - 127.0.0.1:${FORWARD_DB_PORT:-5432}:5432

  mailpit:
    extends:
      file: deploy/compose.yml
      service: mailpit
    ports:
      - 127.0.0.1:${FORWARD_SMTP_PORT:-1025}:1025
      - 127.0.0.1:${FORWARD_MAILPIT_PORT:-8025}:8025

  jaeger:
    extends:
      file: deploy/compose.yml
      service: jaeger
    ports:
      - 127.0.0.1:${FORWARD_JAEGER_PORT:-16686}:16686  # Jaeger UI
      - 127.0.0.1:${FORWARD_OTLP_GRPC_PORT:-4317}:4317 # OTLP gRPC
      - 127.0.0.1:${FORWARD_OTLP_HTTP_PORT:-4318}:4318 # OTLP HTTP

networks:
  default:
    name: elysia-stack
