services:
  app:
    image: ghcr.io/feryardiant/learn-bun-elysia:${STAGING_BRANCH:-latest}
    container_name: elysia-app
    ports:
      - ${FORWARD_APP_PORT:-3000}:3000
    env_file:
      - path: .env
        required: true
      - path: .env.staging
        required: false
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      NODE_ENV: ${NODE_ENV:-staging}
      APP_URL: ${APP_URL:-http://localhost:${FORWARD_APP_PORT:-3000}}
      APP_DOMAIN: ${APP_DOMAIN:-localhost}
      BASE_PATH: ${BASE_PATH:-}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      AUTH_SECRET: ${AUTH_SECRET:-}
      DB_NAME: ${DB_NAME:-elysia_app}
      DB_PORT: 5432
      DB_HOST: ${DB_HOST:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-secret}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  postgres:
    image: postgres:${DB_VERSION:-17.7}-${BASE_OS:-alpine}${BASE_VERSION:-3.23}
    container_name: elysia-db
    ports:
      - ${FORWARD_DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-secret}
      POSTGRES_DB: ${DB_NAME:-elysia_app}
    volumes:
      - ./tmp/init-db.sql:/docker-entrypoint-initdb.d/10-init-db.sql
      - ./tmp/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-elysia_app}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  default:
    name: elysia-stack
