x-deploy: &deploy
  resources:
    limits:
      cpus: '0.5'
      memory: 256M

x-healthcheck: &healthcheck
  interval: 10s
  timeout: 5s
  retries: 3

services:
  app:
    image: ghcr.io/feryardiant/learn-bun-elysia:${STAGING_BRANCH:-latest}
    container_name: elysia-app
    build:
      context: ..
      dockerfile: deploy/docker/dockerfile
      pull: false
      target: runtime
      args:
        APP_NAME: ${APP_NAME:-learn-elysia}
        APP_VERSION: ${APP_VERSION:-0.0.0-local}
        BASE_OS: ${BASE_OS:-alpine}
        BASE_VERSION: ${BASE_VERSION:-3.23}
        BUN_VERSION: ${BUN_VERSION:-1.4}
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
      jaeger:
        condition: service_started
    # env_file:
    #   - path: ../.env
    #     required: true
    environment:
      PORT: 3000
      HOST: 0.0.0.0

      APP_DOMAIN: ${APP_DOMAIN:-localhost}
      APP_URL: ${APP_URL:-http://${APP_DOMAIN:-localhost}:${FORWARD_APP_PORT:-3000}}
      BASE_PATH: ${BASE_PATH:-}
      LOG_LEVEL: ${LOG_LEVEL:-info}

      AUTH_SECRET: ${AUTH_SECRET:-}

      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-secret}
      DB_NAME: ${DB_NAME:-elysia_app}

      # Email
      SMTP_HOST: ${SMTP_HOST:-mailpit}
      SMTP_PORT: 1025
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASS: ${SMTP_PASS:-}
      SMTP_EMAIL: ${SMTP_EMAIL:-noreply@${APP_DOMAIN:-example.com}}

      # OTEL
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4318}
    deploy: *deploy

  postgres:
    image: postgres:${DB_VERSION:-17.7}-${BASE_OS:-alpine}${BASE_VERSION:-3.23}
    container_name: elysia-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-secret}
      POSTGRES_DB: ${DB_NAME:-elysia_app}
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/10-init-db.sql
      - ./local/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-elysia_app}"]
      <<: *healthcheck
    deploy: *deploy

  mailpit:
    image: axllent/mailpit:v1.29
    container_name: elysia-mail
    environment:
      MP_DATABASE: /data/mailpit.db
    volumes:
      - ./local/mailpit:/data

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.15.0
    container_name: elysia-otel
    command: ["--config=/etc/jaeger/config.yml"]
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - ./jaeger-ui-config.json:/etc/jaeger/config-ui.json
      - ./jaeger-config.yml:/etc/jaeger/config.yml
      - ./local/jaeger:/tmp
    deploy: *deploy
