# syntax=docker/dockerfile:1.4
# -----------------------------------
# Stage 1: Build
ARG BUN_VERSION="1.4"
ARG BASE_OS="alpine"

FROM oven/bun:${BUN_VERSION}-${BASE_OS} AS build

WORKDIR /app

RUN apk add --no-cache git

ENV NODE_ENV=devcontainer PORT=3000 HOST=0.0.0.0

EXPOSE ${PORT} 4000

ENTRYPOINT [ "bun", "run", ".devcontainer/init.ts" ]
