# syntax=docker/dockerfile:1.4
# -----------------------------------
# Stage 1: Build
ARG BUN_VERSION="1.3.3"
ARG BASE_OS="alpine"

FROM oven/bun:${BUN_VERSION}-${BASE_OS} AS build

WORKDIR /app

COPY . .

RUN apk add --no-cache curl git

RUN bun ci --no-cache --ignore-scripts

ENV NODE_ENV=devcontainer PORT=3000 HOST=0.0.0.0 PATH="/app:$PATH"

EXPOSE ${PORT} 4000

HEALTHCHECK --interval=10s --timeout=5s --retries=3 \
  CMD curl -f http://localhost:${PORT}/health || exit 1

ENTRYPOINT [ "bun", "run", ".devcontainer/init.ts" ]
