name: Distribute
run-name: "dist(${{ github.event.workflow_run.head_branch }}): docker build for `${{ github.event.workflow_run.head_sha }}`"

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    if: github.event.workflow_run.conclusion == 'success'
    uses: projek-xyz/actions/.github/workflows/prepare.yml@main

    permissions:
      contents: read
      pull-requests: write

  docker:
    name: Build Docker Images
    needs: prepare
    if: needs.prepare.outputs.should-build == '1'
    uses: projek-xyz/actions/.github/workflows/docker.yml@main
    with:
      build-args: |
        BUN_VERSION=${{ vars.BUN_VERSION || '1.4.2' }}
        BASE_OS=alpine
        APP_NAME=elysia-app
        APP_VERSION=${{ needs.prepare.outputs.project-version }}
      docker-file: deploy/docker/elysia-app.dockerfile
      image-tag: ${{ needs.prepare.outputs.project-version }}
      image-slug: ${{ needs.prepare.outputs.branch-slug }}
      image-labels: |
        org.opencontainers.image.author=${{ github.repository_owner }}
        org.opencontainers.image.licenses=MIT

    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

  api-schema:
    name: API Schema Artifact
    if: github.event_name != 'pull_request' || needs.prepare.outputs.pr-number == ''
    needs: [prepare, docker]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    env:
      DB_NAME: ${{ github.repository_owner }}
      DB_USER: ${{ github.repository_owner }}
      DB_PASS: secret
      BUN_VERSION: ${{ vars.BUN_VERSION || '1.4.2' }}

    services:
      postgres:
        image: postgres:${{ vars.DB_VERSION || '17.7' }}
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASS }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd=pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      app:
        image: ${{ needs.docker.outputs.image-url }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ github.token }}
        env:
          NODE_ENV: staging
          APP_SECRET: not-secure-secret
          LOG_LEVEL: debug
          DB_HOST: postgres
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASS: ${{ env.DB_PASS }}
        ports:
          - 3000:3000

    steps:
      - name: Set up bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Generate API schema
        env:
          APP_URL: http://localhost:${{ job.services.app.ports['3000'] }}
        run: |
          bunx openapi-typescript $APP_URL/docs/json -o elysia-app.schema.d.ts

      - name: Upload schema artifacts
        id: api-schema
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: api-schema_${{ needs.prepare.outputs.branch-slug }}
          path: elysia-app.schema.d.ts
          retention-days: 30
          overwrite: true

  stress-test:
    name: Stress Test
    if: github.event_name != 'pull_request' || needs.prepare.outputs.pr-number == ''
    needs: [prepare, docker]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    env:
      DB_NAME: ${{ github.repository_owner }}
      DB_USER: ${{ github.repository_owner }}
      DB_PASS: secret

    services:
      postgres:
        image: postgres:${{ vars.DB_VERSION || '17.7' }}
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASS }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd=pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      app:
        image: ${{ needs.docker.outputs.image-url }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ github.token }}
        env:
          NODE_ENV: staging
          APP_SECRET: not-secure-secret
          LOG_LEVEL: debug
          DB_HOST: postgres
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASS: ${{ env.DB_PASS }}
        ports:
          - 3000:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup k6
        uses: grafana/setup-k6-action@db07bd9765aac508ef18982e52ab937fe633a065 # v1.2.1

      - name: Run k6 load test
        env:
          APP_URL: http://localhost:${{ job.services.app.ports['3000'] }}
        run: |
          k6 run scripts/throughput.ts --summary-export=load-performance.json

      - name: Create Summary
        if: always()
        run: |
          echo "### Load Test Results 🚀" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY
          echo "| Total Requests | $(jq .metrics.http_reqs.count load-performance.json) |" >> $GITHUB_STEP_SUMMARY
          echo "| Failed Requests | $(jq .metrics.http_req_failed.count load-performance.json) |" >> $GITHUB_STEP_SUMMARY
          echo "| Avg Duration | $(jq .metrics.http_req_duration.avg load-performance.json)ms |" >> $GITHUB_STEP_SUMMARY
          echo "| P95 Duration | $(jq '.metrics.http_req_duration["p(95)"]' load-performance.json)ms |" >> $GITHUB_STEP_SUMMARY

  k8s:
    name: Kubernetes
    if: github.event.workflow_run.event == 'push' && needs.prepare.outputs.should-deploy == '1'
    needs: [prepare, docker, stress-test]
    uses: ./.github/workflows/k8s.yml
    secrets: inherit

    permissions:
      contents: write

    with:
      deploy-env: development # make it static for now
      image-tag: ${{ needs.prepare.outputs.project-version }}
      repo-name: ${{ needs.prepare.outputs.project-repo-name }}
      service-name: elysia-app
